"""Regenerate ``clients.txt`` from the bundled ``index.html`` caps list.

The HTML is a table of ``<a href="clients/ICON.png">…</a> <b>Name</b> caps<br>``
rows.  This script normalizes it into the simple tab-separated mapping used at
runtime by :mod:`stanza_im.include.clients`:

    caps-prefix <TAB> client name <TAB> icon file

Run from anywhere::

    python3 resources/clients/build_clients.py
"""
from __future__ import annotations

import html
import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
_INDEX = os.path.join(_HERE, "index.html")
_OUTPUT = os.path.join(_HERE, "clients.txt")

# Known typos in the source list (referenced name -> real file).
_ICON_FIXES = {
    "convarsations.png": "conversations.png",
    "sawin-iphone.png": "sawim-iphone.png",
}

_ROW_RE = re.compile(
    r'<a href="clients/([^"]+)">.*?</a>\s*<b>(.*?)</b>'
    r'((?:(?!<(?:/?div|/?p|br|a)\b).)*)', re.S)
_KEEP_RE = re.compile(r"^(https?://|urn:)")


def _text(value: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", value)).strip()


def _clean_caps(token: str) -> str:
    token = _text(token).strip().strip(",;").strip()
    # The source uses a Cyrillic 'р' inside "http" (httр://).
    token = token.replace("htt\u0440", "http")
    token = re.sub(r"#(android|blacksmith-m\.1|security-bot)$", "", token)
    token = re.sub(r"\?QIP\*$", "", token)
    return token.rstrip("\u00b1*~#").strip()


def _caps_tokens(caps: str) -> list[str]:
    tokens = []
    for raw in re.split(r",|\s+\u0438\s+", _text(caps)):
        token = _clean_caps(raw)
        if token and _KEEP_RE.match(token):
            tokens.append(token)
    return tokens


def _alt_scheme(token: str) -> str:
    """The same URL with the other http(s) scheme (clients are inconsistent)."""
    if token.startswith("http://"):
        return "https://" + token[len("http://"):]
    if token.startswith("https://"):
        return "http://" + token[len("https://"):]
    return ""


def build() -> list[tuple[str, str, str]]:
    with open(_INDEX, encoding="utf-8") as fh:
        source = fh.read()
    entries: dict[str, tuple[str, str, str]] = {}
    for icon, name, caps in _ROW_RE.findall(source):
        icon = _ICON_FIXES.get(icon, icon)
        name = _text(name)
        for token in _caps_tokens(caps):
            entries.setdefault(token, (token, name or token, icon))
    for token, (_, name, icon) in list(entries.items()):
        alt = _alt_scheme(token)
        if alt and alt not in entries:
            entries[alt] = (alt, name, icon)
    return sorted(entries.values(), key=lambda e: (-len(e[0]), e[0]))


def main() -> None:
    entries = build()
    lines = ["# caps-prefix\tclient name\ticon file",
             "# Generated by build_clients.py from index.html"]
    lines += ["\t".join(entry) for entry in entries]
    with open(_OUTPUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} caps mappings to {_OUTPUT}")


if __name__ == "__main__":
    main()
