"""Emoji catalogue for the reaction picker (XEP-0444).

A compact, dependency-free catalogue: categories of Unicode emoji with a few
English search keywords each.  Glyphs are drawn by the system font, so no
image assets are needed.  ``search()`` matches the keywords (and the glyph
itself), case-insensitively.
"""
from __future__ import annotations

# (category key, emoji, keywords)
_EMOJI: tuple[tuple[str, str, str], ...] = (
    # ── Smileys & Emotion ────────────────────────────────────────
    ("smileys", "😀", "grin grinning smile happy"),
    ("smileys", "😃", "smiley happy"),
    ("smileys", "😄", "smile happy joy"),
    ("smileys", "😁", "grin beam"),
    ("smileys", "😆", "laugh satisfied"),
    ("smileys", "😅", "sweat smile relief"),
    ("smileys", "🤣", "rofl rolling laugh"),
    ("smileys", "😂", "joy tears laugh"),
    ("smileys", "🙂", "slight smile"),
    ("smileys", "🙃", "upside down"),
    ("smileys", "😉", "wink"),
    ("smileys", "😊", "blush smile"),
    ("smileys", "😇", "innocent angel halo"),
    ("smileys", "🥰", "love adore hearts"),
    ("smileys", "😍", "heart eyes love"),
    ("smileys", "🤩", "star struck wow"),
    ("smileys", "😘", "kiss blow"),
    ("smileys", "😗", "kissing"),
    ("smileys", "😚", "kissing closed eyes"),
    ("smileys", "😙", "kissing smiling"),
    ("smileys", "🥲", "smile tear"),
    ("smileys", "😋", "yum tasty"),
    ("smileys", "😛", "tongue"),
    ("smileys", "😜", "wink tongue"),
    ("smileys", "🤪", "zany crazy"),
    ("smileys", "😝", "squint tongue"),
    ("smileys", "🤑", "money mouth"),
    ("smileys", "🤗", "hug hugs"),
    ("smileys", "🤭", "hand mouth oops"),
    ("smileys", "🤫", "shush quiet"),
    ("smileys", "🤔", "thinking think"),
    ("smileys", "🤐", "zipper mouth"),
    ("smileys", "🤨", "raised eyebrow"),
    ("smileys", "😐", "neutral"),
    ("smileys", "😑", "expressionless"),
    ("smileys", "😶", "no mouth speechless"),
    ("smileys", "😏", "smirk"),
    ("smileys", "😒", "unamused"),
    ("smileys", "🙄", "roll eyes"),
    ("smileys", "😬", "grimace"),
    ("smileys", "🤥", "lying"),
    ("smileys", "😌", "relieved"),
    ("smileys", "😔", "pensive sad"),
    ("smileys", "😪", "sleepy"),
    ("smileys", "🤤", "drool"),
    ("smileys", "😴", "sleep zzz"),
    ("smileys", "😷", "mask sick"),
    ("smileys", "🤒", "thermometer sick"),
    ("smileys", "🤕", "bandage hurt"),
    ("smileys", "🤢", "nauseated sick"),
    ("smileys", "🤮", "vomit"),
    ("smileys", "🤧", "sneeze"),
    ("smileys", "🥵", "hot"),
    ("smileys", "🥶", "cold"),
    ("smileys", "🥴", "woozy"),
    ("smileys", "😵", "dizzy dead"),
    ("smileys", "🤯", "explode mind blown"),
    ("smileys", "🤠", "cowboy"),
    ("smileys", "🥳", "party hat celebrate"),
    ("smileys", "😎", "cool sunglasses"),
    ("smileys", "🤓", "nerd glasses"),
    ("smileys", "🧐", "monocle"),
    ("smileys", "😕", "confused"),
    ("smileys", "😟", "worried"),
    ("smileys", "🙁", "frown"),
    ("smileys", "😮", "open mouth wow"),
    ("smileys", "😯", "hushed surprise"),
    ("smileys", "😲", "astonished"),
    ("smileys", "😳", "flushed blush"),
    ("smileys", "🥺", "pleading please"),
    ("smileys", "😦", "frown open"),
    ("smileys", "😧", "anguished"),
    ("smileys", "😨", "fearful"),
    ("smileys", "😰", "anxious sweat"),
    ("smileys", "😥", "sad relieved"),
    ("smileys", "😢", "cry sad tear"),
    ("smileys", "😭", "sob cry loud"),
    ("smileys", "😱", "scream fear"),
    ("smileys", "😖", "confounded"),
    ("smileys", "😣", "persevere"),
    ("smileys", "😞", "disappointed sad"),
    ("smileys", "😓", "downcast sweat"),
    ("smileys", "😩", "weary"),
    ("smileys", "😫", "tired"),
    ("smileys", "🥱", "yawn"),
    ("smileys", "😤", "triumph huff"),
    ("smileys", "😡", "rage angry"),
    ("smileys", "😠", "angry"),
    ("smileys", "🤬", "cursing swear"),
    ("smileys", "😈", "devil smiling"),
    ("smileys", "👿", "devil angry"),
    ("smileys", "💀", "skull dead"),
    ("smileys", "💩", "poop"),
    ("smileys", "🤡", "clown"),
    ("smileys", "👻", "ghost"),
    ("smileys", "👽", "alien"),
    ("smileys", "🤖", "robot"),
    # ── Gestures & People ────────────────────────────────────────
    ("gestures", "👍", "thumbs up like ok"),
    ("gestures", "👎", "thumbs down dislike"),
    ("gestures", "👌", "ok perfect"),
    ("gestures", "🤌", "pinched"),
    ("gestures", "✌️", "victory peace"),
    ("gestures", "🤞", "fingers crossed luck"),
    ("gestures", "🤟", "love you"),
    ("gestures", "🤘", "rock horns"),
    ("gestures", "🤙", "call me"),
    ("gestures", "👈", "point left"),
    ("gestures", "👉", "point right"),
    ("gestures", "👆", "point up"),
    ("gestures", "👇", "point down"),
    ("gestures", "☝️", "point up one"),
    ("gestures", "✋", "hand stop"),
    ("gestures", "🤚", "raised back hand"),
    ("gestures", "🖐️", "hand fingers"),
    ("gestures", "🖖", "vulcan spock"),
    ("gestures", "👋", "wave hello hi"),
    ("gestures", "🤝", "handshake deal"),
    ("gestures", "🙏", "pray thanks please"),
    ("gestures", "✍️", "writing"),
    ("gestures", "💪", "muscle strong"),
    ("gestures", "🫡", "salute"),
    ("gestures", "🫶", "heart hands love"),
    ("gestures", "👏", "clap applause"),
    ("gestures", "🙌", "raise hands hooray"),
    ("gestures", "👐", "open hands"),
    ("gestures", "🤲", "palms up"),
    ("gestures", "🤝", "shake"),
    ("gestures", "👊", "fist bump"),
    ("gestures", "✊", "fist raised"),
    ("gestures", "🤛", "fist left"),
    ("gestures", "🤜", "fist right"),
    ("gestures", "🤦", "facepalm"),
    ("gestures", "🤷", "shrug dunno"),
    # ── Hearts & Love ────────────────────────────────────────────
    ("hearts", "❤️", "red heart love"),
    ("hearts", "🧡", "orange heart"),
    ("hearts", "💛", "yellow heart"),
    ("hearts", "💚", "green heart"),
    ("hearts", "💙", "blue heart"),
    ("hearts", "💜", "purple heart"),
    ("hearts", "🖤", "black heart"),
    ("hearts", "🤍", "white heart"),
    ("hearts", "🤎", "brown heart"),
    ("hearts", "💔", "broken heart"),
    ("hearts", "💕", "two hearts love"),
    ("hearts", "💞", "revolving hearts"),
    ("hearts", "💓", "beating heart"),
    ("hearts", "💗", "growing heart"),
    ("hearts", "💖", "sparkling heart"),
    ("hearts", "💘", "arrow heart cupid"),
    ("hearts", "💝", "gift heart"),
    ("hearts", "💟", "heart decoration"),
    ("hearts", "😻", "heart eyes cat"),
    # ── Animals & Nature ─────────────────────────────────────────
    ("nature", "🐶", "dog"),
    ("nature", "🐱", "cat"),
    ("nature", "🐭", "mouse"),
    ("nature", "🐹", "hamster"),
    ("nature", "🐰", "rabbit bunny"),
    ("nature", "🦊", "fox"),
    ("nature", "🐻", "bear"),
    ("nature", "🐼", "panda"),
    ("nature", "🐨", "koala"),
    ("nature", "🐯", "tiger"),
    ("nature", "🦁", "lion"),
    ("nature", "🐮", "cow"),
    ("nature", "🐷", "pig"),
    ("nature", "🐸", "frog"),
    ("nature", "🐵", "monkey"),
    ("nature", "🐔", "chicken"),
    ("nature", "🐧", "penguin"),
    ("nature", "🐦", "bird"),
    ("nature", "🦆", "duck"),
    ("nature", "🦉", "owl"),
    ("nature", "🐴", "horse"),
    ("nature", "🦄", "unicorn"),
    ("nature", "🐝", "bee"),
    ("nature", "🦋", "butterfly"),
    ("nature", "🐌", "snail"),
    ("nature", "🐞", "ladybug"),
    ("nature", "🐢", "turtle"),
    ("nature", "🐍", "snake"),
    ("nature", "🐙", "octopus"),
    ("nature", "🦀", "crab"),
    ("nature", "🐬", "dolphin"),
    ("nature", "🐳", "whale"),
    ("nature", "🦈", "shark"),
    ("nature", "🌵", "cactus"),
    ("nature", "🌲", "tree"),
    ("nature", "🌳", "tree"),
    ("nature", "🍀", "clover luck"),
    ("nature", "🌸", "blossom flower"),
    ("nature", "🌹", "rose flower"),
    ("nature", "🌻", "sunflower"),
    ("nature", "🌈", "rainbow"),
    ("nature", "⭐", "star"),
    ("nature", "🌟", "glowing star"),
    ("nature", "✨", "sparkles"),
    ("nature", "⚡", "lightning zap"),
    ("nature", "🔥", "fire lit"),
    ("nature", "❄️", "snowflake cold"),
    ("nature", "☀️", "sun sunny"),
    ("nature", "🌙", "moon night"),
    # ── Food & Drink ─────────────────────────────────────────────
    ("food", "🍏", "apple green"),
    ("food", "🍎", "apple red"),
    ("food", "🍌", "banana"),
    ("food", "🍇", "grapes"),
    ("food", "🍓", "strawberry"),
    ("food", "🍒", "cherry"),
    ("food", "🍑", "peach"),
    ("food", "🍍", "pineapple"),
    ("food", "🥑", "avocado"),
    ("food", "🍅", "tomato"),
    ("food", "🥕", "carrot"),
    ("food", "🌽", "corn"),
    ("food", "🍞", "bread"),
    ("food", "🧀", "cheese"),
    ("food", "🍕", "pizza"),
    ("food", "🍔", "burger"),
    ("food", "🍟", "fries"),
    ("food", "🌭", "hotdog"),
    ("food", "🌮", "taco"),
    ("food", "🍣", "sushi"),
    ("food", "🍜", "noodles ramen"),
    ("food", "🍦", "ice cream"),
    ("food", "🍩", "donut"),
    ("food", "🍪", "cookie"),
    ("food", "🎂", "cake birthday"),
    ("food", "🍰", "cake"),
    ("food", "🍫", "chocolate"),
    ("food", "🍬", "candy"),
    ("food", "☕", "coffee"),
    ("food", "🍵", "tea"),
    ("food", "🍺", "beer"),
    ("food", "🍻", "beers cheers"),
    ("food", "🍷", "wine"),
    ("food", "🥂", "champagne cheers"),
    ("food", "🍸", "cocktail"),
    # ── Activities & Objects ─────────────────────────────────────
    ("objects", "⚽", "soccer ball"),
    ("objects", "🏀", "basketball"),
    ("objects", "🏈", "football"),
    ("objects", "⚾", "baseball"),
    ("objects", "🎾", "tennis"),
    ("objects", "🏐", "volleyball"),
    ("objects", "🎱", "billiards"),
    ("objects", "🏓", "ping pong"),
    ("objects", "🎮", "game controller"),
    ("objects", "🎲", "dice"),
    ("objects", "🎯", "darts target"),
    ("objects", "🎳", "bowling"),
    ("objects", "🎤", "microphone sing"),
    ("objects", "🎧", "headphones"),
    ("objects", "🎵", "music note"),
    ("objects", "🎶", "music notes"),
    ("objects", "🎸", "guitar"),
    ("objects", "🎹", "piano"),
    ("objects", "🥁", "drum"),
    ("objects", "🎬", "clapper movie"),
    ("objects", "📷", "camera photo"),
    ("objects", "💡", "idea light bulb"),
    ("objects", "🔔", "bell"),
    ("objects", "🔑", "key"),
    ("objects", "🔒", "lock"),
    ("objects", "🔓", "unlock"),
    ("objects", "💰", "money bag"),
    ("objects", "💎", "gem diamond"),
    ("objects", "⚙️", "gear settings"),
    ("objects", "🔧", "wrench tool"),
    ("objects", "🔨", "hammer"),
    ("objects", "🚀", "rocket launch"),
    ("objects", "🛰️", "satellite"),
    ("objects", "✈️", "airplane plane"),
    ("objects", "🚗", "car"),
    ("objects", "🚲", "bicycle"),
    ("objects", "🏠", "house home"),
    ("objects", "🏢", "building office"),
    ("objects", "📱", "phone mobile"),
    ("objects", "💻", "laptop computer"),
    ("objects", "⌨️", "keyboard"),
    ("objects", "🖥️", "desktop computer"),
    ("objects", "🖱️", "mouse"),
    ("objects", "📚", "books"),
    ("objects", "📖", "open book"),
    ("objects", "✏️", "pencil"),
    ("objects", "📝", "memo note"),
    ("objects", "📌", "pin"),
    ("objects", "📎", "paperclip"),
    ("objects", "✂️", "scissors"),
    ("objects", "📦", "package box"),
    ("objects", "🎁", "gift present"),
    ("objects", "🎉", "party tada celebrate"),
    ("objects", "🎊", "confetti"),
    ("objects", "🎈", "balloon"),
    # ── Symbols ──────────────────────────────────────────────────
    ("symbols", "✅", "check done ok"),
    ("symbols", "❌", "cross no wrong"),
    ("symbols", "✔️", "check mark"),
    ("symbols", "❗", "exclamation"),
    ("symbols", "❓", "question"),
    ("symbols", "⚠️", "warning"),
    ("symbols", "💯", "hundred perfect"),
    ("symbols", "💤", "sleep zzz"),
    ("symbols", "💢", "anger symbol"),
    ("symbols", "♻️", "recycle"),
    ("symbols", "🔞", "no entry eighteen"),
    ("symbols", "🔴", "red circle"),
    ("symbols", "🟠", "orange circle"),
    ("symbols", "🟡", "yellow circle"),
    ("symbols", "🟢", "green circle"),
    ("symbols", "🔵", "blue circle"),
    ("symbols", "🟣", "purple circle"),
    ("symbols", "⚫", "black circle"),
    ("symbols", "⚪", "white circle"),
    ("symbols", "🟥", "red square"),
    ("symbols", "🟩", "green square"),
    ("symbols", "🟦", "blue square"),
    # ── Flags ────────────────────────────────────────────────────
    ("flags", "🏁", "chequered flag finish"),
    ("flags", "🚩", "triangular flag"),
    ("flags", "🎌", "crossed flags"),
    ("flags", "🏴", "black flag"),
    ("flags", "🏳️", "white flag"),
    ("flags", "🏳️‍🌈", "rainbow flag pride"),
    ("flags", "🇷🇺", "russia flag"),
    ("flags", "🇺🇦", "ukraine flag"),
    ("flags", "🇺🇸", "usa flag"),
    ("flags", "🇬🇧", "uk flag"),
    ("flags", "🇩🇪", "germany flag"),
    ("flags", "🇫🇷", "france flag"),
    ("flags", "🇪🇸", "spain flag"),
    ("flags", "🇮🇹", "italy flag"),
    ("flags", "🇨🇳", "china flag"),
    ("flags", "🇯🇵", "japan flag"),
)

# Quick-access favourites shown first in the picker / used as defaults.
FAVOURITES: tuple[str, ...] = (
    "👍", "❤️", "😂", "😮", "😢", "🎉", "👎", "🔥", "🙏", "👌",
)


def categories() -> list[str]:
    """Return the category keys in catalogue order (de-duplicated)."""
    seen: list[str] = []
    for category, _emoji, _kw in _EMOJI:
        if category not in seen:
            seen.append(category)
    return seen


def by_category(category: str) -> list[str]:
    """Return the emoji of one *category*."""
    return [emoji for cat, emoji, _kw in _EMOJI if cat == category]


def all_emoji() -> list[str]:
    """Return every emoji in the catalogue (de-duplicated, order kept)."""
    seen: list[str] = []
    for _cat, emoji, _kw in _EMOJI:
        if emoji not in seen:
            seen.append(emoji)
    return seen


def search(query: str, limit: int = 60) -> list[str]:
    """Return emoji matching *query* by keyword (or the glyph itself)."""
    query = (query or "").strip().casefold()
    if not query:
        return []
    hits: list[str] = []
    for _cat, emoji, kw in _EMOJI:
        if query == emoji or query in kw:
            if emoji not in hits:
                hits.append(emoji)
        if len(hits) >= limit:
            break
    return hits
